# Usamos la imagen oficial de Playwright con Python
FROM mcr.microsoft.com/playwright/python:v1.61.0-jammy

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Primero copiamos los requerimientos e instalamos dependencias de Python
# Esto permite que Docker cachee esta capa y sea más rápido en futuras builds
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el resto del código fuente
COPY . .

# Exponemos el puerto donde corre FastAPI
EXPOSE 8000

# Comando para ejecutar tu API
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]